services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'  # Next.js用
      - "5555:5555"  # Prisma Studio用
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
     - DATABASE_URL=postgresql://user:password@db:5432/kudos_db?schema=public
     - PRISMA_STUDIO_HOST=0.0.0.0
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kudos_db
    ports:
      - '5432:5432'
    volumes:
     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: